name: "Beacon Works - DangerJS Workflow"
description: "Workflows utilizing Danger JS"
author: "Beacon Works"
inputs:
  dangerfile:
    description: "Location of dangerfile"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dangerfile }}
