# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions#about-yaml-syntax-for-github-actions
name: "Beacon Works"
description: "Runs Danger JS action configured for Beacon Works"
inputs:
  manual-merge-label:
    description: "The GitHub issue/label to use to disable the auto-merge feature"
    required: true
    default: "manual merge"
runs:
  using: "node12"
  main: "dist/index.js"
