name: 'Beacon Works'
description: 'Runs Danger JS action configured for Beacon Works'
inputs:
  manual-merge-label:
    description: 'The GitHub issue/label to use to disable the auto-merge feature'
    default: 'manual merge'
runs:
  using: 'node12'
  main: 'dist/index.js'
