name: dangerjs

on:
  status: {}
  pull_request:
    types: [edited, labeled, unlabeled, ready_for_review, review_requested, review_request_removed]
    branches-ignore: [staging, production, master]
  pull_request_review:
    types: [submitted]

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Wait for status checks'
        id: statuschecks
        uses: 'WyriHaximus/github-action-wait-for-status@master'
        with:
          ignoreActions: automerge
          checkInterval: 30
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run automerge check
        # - uses: beacon-works/dangerjs-workflows@master
        uses: ./
        with:
          dangerfile: './dangerflows/automerge.ts'
        if: steps.statuschecks.outputs.status == 'success'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.BEACON_BOT_PERSONAL_ACCESS_TOKEN }}
