on:
  push:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  beacon_works_test:
    runs-on: ubuntu-latest
    name: Beacon Works PR Workflow
    steps:
      - uses: actions/checkout@v1
      - name: Run workflow checks on PRs
        uses: danger/danger-js@9.2.6
        with:
          args: '--dangerfile ./src/allPRs.ts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
