on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  beacon_works_main_test:
    runs-on: ubuntu-latest
    name: Beacon Works Workflow
    steps:
      - uses: actions/checkout@v1
      - name: Run workflow checks on PRs
        uses: ./
        # uses: beacon-works/dangerjs-workflows
        with:
          myInput: 'test input --- cit'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
