name: danger/dangerjs

on: [push]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    name: beacon-works/dangerjs-checks
    steps:
      - uses: actions/checkout@v1
      - name: Run dangerjs checks
        uses: beacon-works/dangerjs-workflows@testing
        # uses: ./
        with:
          dangerfile: "./wrongfilezzzz.ts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.BEACON_BOT_PERSONAL_ACCESS_TOKEN }}
