on: [push]

jobs:
  beacon_works_test:
    runs-on: ubuntu-latest
    name: Beacon Works PR workflow
    steps:
      - uses: actions/checkout@v1
      - name: Hello world action step
        uses: danger/danger-js@9.2.6
        with:
          args: "--dangerfile ./src/dangerfile.ts"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
