name: danger/dangerjs
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  allPRs:
    runs-on: ubuntu-latest
    name: Beacon Works PR Workflow
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install Dependencies
        run: yarn install  --frozen-lockfile
      - name: Run workflow checks on PRs
        run: yarn danger ci --dangerfile ./src/allPRs.ts
        # uses: danger/danger-js@9.2.6
        # with:
        #   args: '--dangerfile ./src/allPRs.ts'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
